networks:
  pathpal-net:
    driver: bridge

services:
  api:
    build: .
    restart: always
    ports:
      - "1323:1323"
      - "8554:8554/udp"       # Pi streams MPEGTS H264 to this port
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - STREAM_UDP_ADDR=udp://0.0.0.0:8554
      - STREAM_FPS=15
      - STREAM_QUALITY=5
    networks:
      - pathpal-net

  db:
    image: postgres:18-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - pathpal-net

volumes:
  postgres_data: